require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/plays", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Play. As you add validations to Play, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Play.create! valid_attributes
      get plays_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      play = Play.create! valid_attributes
      get play_url(play)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_play_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      play = Play.create! valid_attributes
      get edit_play_url(play)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Play" do
        expect {
          post plays_url, params: { play: valid_attributes }
        }.to change(Play, :count).by(1)
      end

      it "redirects to the created play" do
        post plays_url, params: { play: valid_attributes }
        expect(response).to redirect_to(play_url(Play.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Play" do
        expect {
          post plays_url, params: { play: invalid_attributes }
        }.to change(Play, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post plays_url, params: { play: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested play" do
        play = Play.create! valid_attributes
        patch play_url(play), params: { play: new_attributes }
        play.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the play" do
        play = Play.create! valid_attributes
        patch play_url(play), params: { play: new_attributes }
        play.reload
        expect(response).to redirect_to(play_url(play))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        play = Play.create! valid_attributes
        patch play_url(play), params: { play: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested play" do
      play = Play.create! valid_attributes
      expect {
        delete play_url(play)
      }.to change(Play, :count).by(-1)
    end

    it "redirects to the plays list" do
      play = Play.create! valid_attributes
      delete play_url(play)
      expect(response).to redirect_to(plays_url)
    end
  end
end
